### ISSUE TITLE
Maturity

### ISSUE THREAD

**Issue by lroal** [panates/lightning-pool#2]
Hello.
I am considering using your lib for pooling against mysql, sqlite and pg. I have been using generic-pool for some years, but upgrading to latest major gave me some surprises. The nodejs program never exits even though all clients are released. And I am also worried about the number of open issues - some of them quite old. Then I stumbled into your lightning-pool. It has few downloads, but the lib itself seems well written witten and maintained. I haven't tested it yet, but will do. 
1) Do you consider it mature enough for production ?
2) Is it used in any  production systems ?

**Comment by erayhanoglu** [comment]
Hi,
I can really understand you. We have been using generic-pool in our products and faced a lot of issues like you had. We develop enterprise level applications. So that issues are unacceptable. This is why we decided to create a stable and better pooling library. As for the answers to your questions, we developed it for our needs and we use it in our enterprise applications. For very long time we had no issue. If you face any issue, you can contact us any time.

**Comment by lroal** [comment]
Thanks
